name = "Hone"
grammar = "hone"
path_suffixes = ["hn"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
word_characters = ["_"]
tab_size = 4
hard_tabs = false

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
